### ISSUE TITLE
loading pipeline is failing

### ISSUE THREAD

**Issue by vadithya1989** [EOSC-LOFAR/lofar_workflow_api#3]
After. selecting an observation the form does not load completely on the lta_lofar_api. service I get the following error:

```python
AttributeError: module 'LGPPP_LOFAR_pipeline' has no attribute 'give_config'
```

**Comment by vadithya1989** [comment]
after running 
``` sh
pipenv install git+https://github.com/EOSC-LOFAR/LGPPP_LOFAR_pipeline.git#egg=lgppp-lofar-pipeline
```
this I have a give config method (updated Pipfle.lock)

**Comment by vadithya1989** [comment]
[Pipfile.lock.zip](https://github.com/EOSC-LOFAR/lofar_workflow_api/files/2645026/Pipfile.lock.zip)

**Comment by HannoSpreeuw** [comment]
But that command is obsolete.
